apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-minimal
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Yashwani14/flask-minimal
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
